Scrolling improvements
codenameone/CodenameOne pull request #3663
Opened 2022-11-28 03:15 UTC by Tianfeng-Chen

Fix #3657 
- Use setOnGenericMotionListener to handle scrolling event
- The logic is detecting input from source ***InputDevice.SOURCE_CLASS_POINTER*** and verify if this event is a motion event with a type of ***MotionEvent.ACTION_SCROLL***
- Get current pointers' X axis and Y axis value
- Using ***event.getAxisValue(MotionEvent.AXIS_VSCROLL)*** to get the moving direction indicator (this can get a value between -1 and 1)
- Use the current Y axis value to calculate the location that the scene should be scrolled to
- Keep the same X axis value and utilize ***scrollTo()*** method to scroll the scene
- Add constrains to verify the desired scrolling location is off the screen.

2022-11-28 03:16 UTC, shai-almog commented
@shannah please review

2023-10-02 14:16 UTC, shannah commented
This PR only appears to apply to peer components, not the general app. 
The most obvious native component to test this on is the webview, but it has its own scrolling functionality, that would need to be tested thoroughly to make sure it doesn't conflict with this.

So, before merging this I need to:
1. Create a test app with no native peer components, to ensure no regressions.
2. Create a test app with a webview, and test with and without this change, and with and without scrolling enabled on the webview to make sure that it doesn't introduce regressions, and verify whether it improves anything.
3. Create a test app with a non-webview native peer component and see how this affects the scrolling on that component.

Also, I sense that this was not the intention of the PR.  The title of the PR and the associated issue make is sound like this was intended to add scroll-wheel support to CN1 android apps in general.  I don't think it does that.
Probably this sort of thing would need to be added in the CodenameOneView class:
https://github.com/codenameone/CodenameOne/blob/master/Ports/Android/src/com/codename1/impl/android/CodenameOneView.java#L372

And possibly the AsyncView also.

2023-10-02 14:18 UTC, shannah requested changes

2023-10-02 14:18 UTC, shannah commented on Ports/Android/src/com/codename1/impl/android/AndroidImplementation.java
> +                            layoutWrapper.setOnGenericMotionListener(new View.OnGenericMotionListener() {
This adds a motion listener to a native peer component. E.g. a webview or other native component.  Not the main view.  Probably we need to add similar in CodenameOneView if we want this to be for general app.

2025-04-12 14:41 UTC, closed without merging